### ISSUE TITLE
MVPレビュー依頼

### ISSUE THREAD

**Issue by Daiki49** [Daiki49/learn-and-latte#43]
お連れ様です。
標記の件について、レビューをお願いいたします。

## 各種情報
サービス名：Learn&Latte
サービスURL：https://learn-and-latte.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] レビュー記事投稿機能
- [x] レビュー記事閲覧機能
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能

## READMEレビュー時から変更した機能
以下の機能について、MVPリリース時までに実装予定でしたが、MVPリリース後の実装予定に変更しました。
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能

## サービスイメージがわかるようなスクリーンショット等
トップページ
[![Image from Gyazo](https://i.gyazo.com/284dd5178ce3cd02cc423e130d2e01e5.jpg)](https://gyazo.com/284dd5178ce3cd02cc423e130d2e01e5)

レビュー投稿画面
[![Image from Gyazo](https://i.gyazo.com/affb152e3344908b77873802b75fb518.png)](https://gyazo.com/affb152e3344908b77873802b75fb518)

レビュー検索結果画面
[![Image from Gyazo](https://i.gyazo.com/a471a5a353f8d6791ccf2f4b58061bb9.png)](https://gyazo.com/a471a5a353f8d6791ccf2f4b58061bb9)

レビュー詳細画面
[![Image from Gyazo](https://i.gyazo.com/4780588bb487d94d2ebfefd34e780268.png)](https://gyazo.com/4780588bb487d94d2ebfefd34e780268)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
